
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git::https://github.com/canonical/maas-terraform-modules.git//modules/maas-config?ref=main"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The credentials and arguments to pass to the MAAS Terraform provider.
  # Type: object({ api_url = string, api_key = string, skip_api_checks = optional(bool, false) })
  maas = {
    api_url = "" # TODO: fill in value
    api_key = "" # TODO: fill in value
  }


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description:
  #       The URL of the boot source to synchronize OS images from
  #       This needs to be a simple streams server
  #   
  # Type: string
  # image_server_url = "http://images.maas.io/ephemeral-v3/stable/"

  # Description:
  #       Configure MAAS to download these images immediately.
  #       Each key is the release name and the value is a map of
  #       architectures and - optionally - sub-architectures.
  #       You must specify all images used in your deployment here, 
  #       including the automatically synced default commissioning image.
  #   
  # Type: map
  # boot_selections = {}

  # Description:
  #       A map of MAAS configuration settings, where key is the setting name and
  #       value is the setting desired value. Note that some settings such as
  #       `commissioning_distro_series` and `default_distro_series` require images 
  #       to be synced before they can be configured. The values for these settings 
  #       must match images defined in `boot_selections`, including the automatically 
  #       synced default commissioning image.
  #   
  # Type: map
  # maas_config = {}

  # Description:
  #       A map of package repositories to supply to MAAS deployed machines, where
  #       key is the repository name and value is a map of package repository
  #       settings
  #   
  # Type: map
  # package_repositories = {}

  # Description:
  #       A map of tags to create, where key is the tag name and value is a map of
  #       tag attributes
  #   
  # Type: map
  # tags = {}

  # Description:
  #       A map of DNS domains to create, where key is the domain name and value is a
  #       map of domain attributes
  #   
  # Type: map
  # domains = {}

  # Description:
  #       A map of DNS domain records to create, where key is the domain name and
  #       value is a set domain records. Each domain record is a map of domain record
  #       attributes
  #   
  # Type: map
  # domain_records = {}

  # Description:
  #       A set of node scripts to create, where each set item points to the script
  #       file path relative to node_scripts_location
  #   
  # Type: set
  # node_scripts = []

  # Description: The path in disk where node script files are located
  # Type: string
  # node_scripts_location = "."

}
