
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git::https://github.com/canonical/maas-terraform-modules.git//modules/maas-deploy?ref=main"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The Juju cloud name to deploy the charmed MAAS model on
  # Type: string
  juju_cloud_name = "" # TODO: fill in value


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The Ubuntu operating system version to install on the MAAS region controller machines
  # Type: string
  # maas_ubuntu_version = "24.04"

  # Description: The Ubuntu operating system version to install on the PostgreSQL machines
  # Type: string
  # postgres_ubuntu_version = "24.04"

  # Description: The Ubuntu operating system version to install on the HAProxy machines
  # Type: string
  # haproxy_ubuntu_version = "24.04"

  # Description: The Juju cloud region to deploy charmed MAAS model on
  # Type: string
  # juju_cloud_region = "default"

  # Description:
  #       Map of Juju model constraints to apply to the MAAS model.
  #       Each key/value pair is rendered as a space-separated "key=value"
  #       constraint string. Useful, for example, to pin the model architecture.
  #
  # Type: map
  # model_constraints = {
  #   arch = "arm64"
  # }

  # Description:
  #       Use the following constraints for the machines
  #       Increase cores and mem for larger MAAS installations
  #       We recommend using virtual machines. If you are curious
  #       you can change the constraints to use containers or physical
  #       hosts but this is untested
  #
  # Type: string
  # maas_constraints = "cores=2 mem=4G virt-type=virtual-machine"

  # Description: Constraints for the Postgres virtual machines
  # Type: string
  # postgres_constraints = "cores=2 mem=4G virt-type=virtual-machine"

  # Description: Constraints for the HAProxy Machines
  # Type: string
  # haproxy_constraints = "cores=1 mem=1G"

  # Description: Constraints for the S3 Integrator machine
  # Type: string
  # s3_constraints = "cores=1 mem=1G"

  # Description:
  #       List of target zones allowed for deploying MAAS PostgreSQL, and HAProxy machines. If provided, machines
  #       are distributed across these zones in round-robin fashion (for example, with 3 zones and 3
  #       machines, each gets a different zone; with 2 zones and 3 machines, the pattern is zone1, zone2,
  #       zone1).
  #
  # Type: list
  # zone_list = []

  # Description: Set this to true to run PostgreSQL in high availability (HA), which will create three PostgreSQL units
  # Type: bool
  # enable_postgres_ha = false

  # Description: Set this to true to run MAAS in high availability (HA), which will create three maas-region controller units
  # Type: bool
  # enable_maas_ha = false

  # Description: Set this to true to run MAAS with HAProxy, which will deploy HAProxy
  # Type: bool
  # enable_haproxy = false

  # Description: The LXD project in which to create the VMs for Juju
  # Type: string
  # lxd_project = "default"

  # Description: Map of additional model configuration parameters (e.g., http-proxy, https-proxy, no-proxy, etc.)
  # Type: map
  # model_config = {}

  # Description: Path to the SSH key to add to the MAAS Juju model
  # Type: string
  # path_to_ssh_key = null

  # Description: Operator channel for PostgreSQL deployment
  # Type: string
  # charm_postgresql_channel = "16/stable"

  # Description: Operator channel revision for PostgreSQL deployment
  # Type: number
  # charm_postgresql_revision = null

  # Description: Operator configuration for PostgreSQL deployment
  # Type: map
  # charm_postgresql_config = {}

  # Description: Operator channel for MAAS Region Controller deployment
  # Type: string
  # charm_maas_region_channel = "3.7/candidate"

  # Description: Operator channel revision for MAAS Region Controller deployment
  # Type: number
  # charm_maas_region_revision = null

  # Description: Operator configuration for MAAS Region Controller deployment
  # Type: map
  # charm_maas_region_config = {}

  # Description: Operator channel for HAProxy deployment
  # Type: string
  # charm_haproxy_channel = "2.8/edge"

  # Description: Operator channel revision for HAProxy deployment
  # Type: number
  # charm_haproxy_revision = null

  # Description: Operator configuration for HAProxy deployment
  # Type: map
  # charm_haproxy_config = {}

  # Description: Operator channel for Keepalived deployment
  # Type: string
  # charm_keepalived_channel = "latest/edge"

  # Description: Operator channel revision for Keepalived deployment
  # Type: number
  # charm_keepalived_revision = null

  # Description: Operator configuration for Keepalived deployment
  # Type: map
  # charm_keepalived_config = {}

  # Description: The MAAS admin username
  # Type: string
  # admin_username = "admin"

  # Description: The MAAS admin password
  # Type: string
  # admin_password = "insecure"

  # Description: The MAAS admin email
  # Type: string
  # admin_email = "admin@maas.io"

  # Description:
  #       The MAAS admin SSH key source. Valid sources include 'lp' for Launchpad and 'gh' for GitHub.
  #       E.g. 'lp:my_launchpad_username'.
  #
  # Type: string
  # admin_ssh_import = ""

  # Description: The MAAS URL to use for the MAAS API. If not given, will default to one derived from the `virtual_ip`, or the HAProxy/MAAS Unit IPs
  # Type: string
  # maas_url = null

  # Description: The optional Virtual IP to use for HA MAAS. If given, will configure the Keepalived subordinate charm.
  # Type: string
  # virtual_ip = null

  # Description: SSL Certificate path, required for MAAS TLS mode operations
  # Type: string
  # ssl_cert_path = null

  # Description: SSL Key path, required for MAAS TLS mode operations
  # Type: string
  # ssl_key_path = null

  # Description: SSL CACert path, optionally used for MAAS TLS mode operations if the ssl_certificate is self signed
  # Type: string
  # ssl_cacert_path = null

  # Description: Whether to enable backup for MAAS and PostgreSQL
  # Type: bool
  # enable_backup = false

  # Description: Operator channel for S3 Integrator deployment
  # Type: string
  # charm_s3_integrator_channel = "1/stable"

  # Description: Operator channel revision for S3 Integrator deployment
  # Type: number
  # charm_s3_integrator_revision = null

  # Description:
  #       Operator configuration for both S3 Integrator deployments.
  #       Configuration for `bucket`, `path`, and `tls-ca-chain` is
  #       skipped even if set, since it is handled by different
  #       Terraform variables
  #
  # Type: map
  # charm_s3_integrator_config = {}

  # Description: The file path of the S3 CA chain, used for HTTPS validation
  # Type: string
  # s3_ca_chain_file_path = ""

  # Description: Access key used to access the S3 backup bucket
  # Type: string
  # s3_access_key = ""

  # Description: Secret key used to access the S3 backup bucket
  # Type: string
  # s3_secret_key = ""

  # Description: Bucket name to store PostgreSQL backups in
  # Type: string
  # s3_bucket_postgresql = "postgresql"

  # Description: Path in the S3 bucket to store PostgreSQL backups in
  # Type: string
  # s3_path_postgresql = "/postgresql"

  # Description: Bucket name to store MAAS backups in
  # Type: string
  # s3_bucket_maas = "maas"

  # Description: Path in the S3 bucket to store MAAS backups in
  # Type: string
  # s3_path_maas = "/maas"

}
