name: Run MAAS Terraform modules Nightly Tests

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  run-full-test:
    environment: testflinger
    runs-on: self-hosted-linux-amd64-noble-private-endpoint-small
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Testflinger attachments
        working-directory: tests
        run: |
          # Copy all modules from root level to tests/terraform/modules
          cp -r ../modules/* terraform/modules/
          # Copy all stacks from root level to tests/terraform/examples
          mkdir -p terraform/examples
          cp -r ../examples/* terraform/examples/
          # Copy all units from root level to tests/terraform/units
          mkdir -p terraform/units
          cp -r ../units/* terraform/units/
          # Create tarball with terraform directory only
          tar -czf tests.tar.gz terraform/
          # Write smoke test flag
          echo "false" > run_smoke_test.txt

      - name: Run on Testflinger
        uses: canonical/testflinger/.github/actions/submit@545ed69f17a5e639a2299e325f5fb199ca9f98af
        with:
          poll: true
          job-path: ./tests/testflinger.yaml
          attachments-relative-to: ./tests/
          client-id: maas-ci
          secret-key: ${{ secrets.TESTFLINGER_SECRET_KEY }}
